version: '3.5'
services:
  php-fpm:
    build: ./docker/php
    image: jefffrade/desafio-logcomex:php-fpm
    restart: on-failure
    container_name: jefffrade-desafio-logcomex-php-fpm
    command: php-fpm
    links:
      - mysql
      - memcached
    volumes:
      - ./:/desafio-logcomex
    networks:
      - app
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: jefffrade/desafio-logcomex:nginx
    restart: on-failure
    container_name: jefffrade-desafio-logcomex-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT_HTTP}:80"
    volumes:
      - ./:/desafio-logcomex
    networks:
      - app
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mysql:
    build: ./docker/mysql
    image: jefffrade/desafio-logcomex:mysql
    restart: on-failure
    container_name: jefffrade-desafio-logcomex-mysql
    volumes:
      - "${DOCKER_DATA_PATH}/mysql:/var/lib/mysql"
      - ./docker/mysql/backup:/backup
    command:
      - "--innodb_use_native_aio=0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - db

  memcached:
    build: ./docker/memcached
    image: jefffrade/desafio-logcomex:memcached
    restart: on-failure
    container_name: jefffrade-desafio-logcomex-memcached
    tty: true
    volumes:
      - ${DOCKER_DATA_PATH}/memcached:/var/run/memcached
    ports:
      - "${MEMCACHED_PORT}:11211"
    networks:
      - app
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 11211 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

networks:
  app:
  db:
